/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kedacom_truetouch_mtc_MtcLib */

#ifndef _Included_com_kedacom_truetouch_mtc_MtcLib
#define _Included_com_kedacom_truetouch_mtc_MtcLib
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_kedacom_truetouch_mtc_MtcLib
 * Method:    SetAndroidObjects
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_kedacom_truetouch_mtc_MtcLib_SetAndroidObjects(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif