# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/common_audio/out
.PHONY: all
all:
	$(MAKE) -C ../.. signal_processing_neon signal_processing vad resampler resampler_unittests signal_processing_unittests vad_unittests
