# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/voice_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. voice_engine_core voe_cmd_test voice_engine_unittests voe_auto_test
