# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test_support_main_threaded_mac
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-Wl,-z,noexecstack \
	-fPIC \
	-Wl,-z,relro \
	-Wl,-z,now \
	-fuse-ld=gold \
	-nostdlib \
	-Wl,--no-undefined \
	-Wl,--exclude-libs=ALL \
	--sysroot=/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//platforms/android-9/arch-arm \
	-Wl,--icf=safe \
	-L/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//sources/cxx-stl/stlport/libs/armeabi-v7a \
	-L/home/ubuntu/workspace/trunk/third_party/android_tools/ndk//sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi-v7a \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lstlport_static \
	/home/ubuntu/workspace/trunk/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-i686/bin/../lib/gcc/arm-linux-androideabi/4.6.x-google/libgcc.a \
	-lc \
	-ldl \
	-lstdc++ \
	-lm

$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: LIBS := $(LIBS)
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a:  FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a
# Add target alias
.PHONY: test_support_main_threaded_mac
test_support_main_threaded_mac: $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a

# Add target alias to "all" target.
.PHONY: all
all: test_support_main_threaded_mac

# Add target alias
.PHONY: test_support_main_threaded_mac
test_support_main_threaded_mac: $(builddir)/libtest_support_main_threaded_mac.a

# Copy this to the static library output path.
$(builddir)/libtest_support_main_threaded_mac.a: TOOLSET := $(TOOLSET)
$(builddir)/libtest_support_main_threaded_mac.a: $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/libtest_support_main_threaded_mac.a
# Short alias for building this static library.
.PHONY: libtest_support_main_threaded_mac.a
libtest_support_main_threaded_mac.a: $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a $(builddir)/libtest_support_main_threaded_mac.a

# Add static library to "all" target.
.PHONY: all
all: $(builddir)/libtest_support_main_threaded_mac.a

