# This file is generated by gyp; do not edit.

export builddir_name ?= ./webrtc/video_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. video_engine_core libvietest libvietest_unittests video_engine_core_unittests vie_auto_test
